## Deliverable 2. Create a Customer Travel Destinations Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config2 import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [2]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("WeatherPy_database2.csv")
city_data_df.head()

,City_ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Current Description
0,0,Punta Arenas,-53.1500,-70.9167,57.20,41,0,29.93,CL,2021-01-21 22:14:37,clear sky
1,1,Smithers,54.7804,-127.1743,23.00,80,90,4.61,CA,2021-01-21 22:14:37,overcast clouds
2,2,Nikolskoye,59.7035,30.7861,14.00,92,90,13.42,RU,2021-01-21 22:14:37,snow
3,3,Carauari,-4.8828,-66.8958,80.22,80,41,2.64,BR,2021-01-21 22:14:37,light rain
4,4,La Rioja,42.2500,-2.5000,46.40,87,40,2.30,ES,2021-01-21 22:14:37,scattered clouds

In [3]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 90

In [4]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)].dropna()

In [5]:

hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Lat", "Lng"]].copy()
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

          City Country  Max Temp      Lat       Lng Hotel Name
3     Carauari      BR     80.22  -4.8828  -66.8958
6      Ibirite      BR     80.60 -20.0219  -44.0589
13      Pangoa      PE     81.28 -12.1167  -73.0000
17       Vaini      TO     80.60 -21.2000 -175.2000
19  Butaritari      KI     79.79   3.0707  172.7902
20     Rikitea      PF     78.78 -23.1203 -134.9692
26    Galesong      ID     78.75  -5.3166  119.3661
32   Amboasary      MG     82.40 -25.0333   46.3833
33  Carutapera      BR     78.08  -1.1950  -46.0200
36     Manggar      ID     77.95  -2.8833  108.2667

In [6]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
3,Carauari,BR,80.22,light rain,-4.8828,-66.8958,
6,Ibirite,BR,80.60,clear sky,-20.0219,-44.0589,
13,Pangoa,PE,81.28,light rain,-12.1167,-73.0000,
17,Vaini,TO,80.60,moderate rain,-21.2000,-175.2000,
19,Butaritari,KI,79.79,moderate rain,3.0707,172.7902,
20,Rikitea,PF,78.78,clear sky,-23.1203,-134.9692,
26,Galesong,ID,78.75,light rain,-5.3166,119.3661,
32,Amboasary,MG,82.40,light rain,-25.0333,46.3833,
33,Carutapera,BR,78.08,light rain,-1.1950,-46.0200,
36,Manggar,ID,77.95,few clouds,-2.8833,108.2667,

In [7]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# Iterate through the DataFrame.
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"

    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
   # Grab the first hotel from the results and store the name.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [8]:
# 7. Drop the rows where there is no Hotel Name.
hotel_df.head(20)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
3,Carauari,BR,80.22,light rain,-4.8828,-66.8958,Hotel Fellip
6,Ibirite,BR,80.60,clear sky,-20.0219,-44.0589,Jangada Hotel
13,Pangoa,PE,81.28,light rain,-12.1167,-73.0000,
17,Vaini,TO,80.60,moderate rain,-21.2000,-175.2000,Keleti Beach Resort
19,Butaritari,KI,79.79,moderate rain,3.0707,172.7902,Isles Sunset Lodge
20,Rikitea,PF,78.78,clear sky,-23.1203,-134.9692,Pension Maro'i
26,Galesong,ID,78.75,light rain,-5.3166,119.3661,Sapriadi Appy
32,Amboasary,MG,82.40,light rain,-25.0333,46.3833,DISCOVERY AMBOASARY
33,Carutapera,BR,78.08,light rain,-1.1950,-46.0200,Lidera
36,Manggar,ID,77.95,few clouds,-2.8833,108.2667,Guest Hotel
37,Saint-Philippe,RE,82.40,broken clouds,-21.3585,55.7679,"Chambres d'hôte ""La Trinité"""
43,Atuona,PF,77.54,broken clouds,-9.8000,-139.0333,Villa Enata
44,Ambovombe,MG,78.78,clear sky,-25.1667,46.0833,RELAHARA
46,Avarua,CK,86.00,light rain,-21.2078,-159.7750,Paradise Inn
49,Mumford,GH,79.34,broken clouds,5.2618,-0.7590,Spanish Villa
53,Kapaa,US,78.80,light rain,22.0752,-159.3190,Sheraton Kauai Resort at Coconut Beach
60,Sechura,PE,81.16,few clouds,-5.5569,-80.8222,Hospedaje Costa Bella
64,Bambous Virieux,MU,79.00,scattered clouds,-20.3428,57.7575,Casa Tia Villa
65,Bengkulu,ID,75.11,light rain,-3.8004,102.2655,Grage Hotel Bengkulu
72,Varzea Da Palma,BR,75.61,overcast clouds,-17.5981,-44.7308,Casa Fernandes

In [9]:
for index, name in hotel_df.iterrows():
    if hotel_df['Hotel Name'][index] == "":
        hotel_df = hotel_df.drop(index)

In [10]:
hotel_df.head(20)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
3,Carauari,BR,80.22,light rain,-4.8828,-66.8958,Hotel Fellip
6,Ibirite,BR,80.60,clear sky,-20.0219,-44.0589,Jangada Hotel
17,Vaini,TO,80.60,moderate rain,-21.2000,-175.2000,Keleti Beach Resort
19,Butaritari,KI,79.79,moderate rain,3.0707,172.7902,Isles Sunset Lodge
20,Rikitea,PF,78.78,clear sky,-23.1203,-134.9692,Pension Maro'i
26,Galesong,ID,78.75,light rain,-5.3166,119.3661,Sapriadi Appy
32,Amboasary,MG,82.40,light rain,-25.0333,46.3833,DISCOVERY AMBOASARY
33,Carutapera,BR,78.08,light rain,-1.1950,-46.0200,Lidera
36,Manggar,ID,77.95,few clouds,-2.8833,108.2667,Guest Hotel
37,Saint-Philippe,RE,82.40,broken clouds,-21.3585,55.7679,"Chambres d'hôte ""La Trinité"""
43,Atuona,PF,77.54,broken clouds,-9.8000,-139.0333,Villa Enata
44,Ambovombe,MG,78.78,clear sky,-25.1667,46.0833,RELAHARA
46,Avarua,CK,86.00,light rain,-21.2078,-159.7750,Paradise Inn
49,Mumford,GH,79.34,broken clouds,5.2618,-0.7590,Spanish Villa
53,Kapaa,US,78.80,light rain,22.0752,-159.3190,Sheraton Kauai Resort at Coconut Beach
60,Sechura,PE,81.16,few clouds,-5.5569,-80.8222,Hospedaje Costa Bella
64,Bambous Virieux,MU,79.00,scattered clouds,-20.3428,57.7575,Casa Tia Villa
65,Bengkulu,ID,75.11,light rain,-3.8004,102.2655,Grage Hotel Bengkulu
72,Varzea Da Palma,BR,75.61,overcast clouds,-17.5981,-44.7308,Casa Fernandes
75,Inirida,CO,76.68,light rain,3.8653,-67.9239,Fuente del Guania Hotel de Lujo

In [11]:
# 8a. Create the output File (CSV)
# Create the output file (CSV).
output_data_file = "WeatherPy_vacation.csv"
# Export the Hotel_Data into a CSV.
hotel_df.to_csv(output_data_file, index_label="City_ID")

In [16]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description} and {Max Temp} °F</dd>
</dl>
"""

# Store the DataFrame Row.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

# Add a heatmap of temperature for the vacation spots and a pop-up marker for each city.
locations = hotel_df[["Lat", "Lng"]]

fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)

marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))